# Site settings
baseURL = "https://www.hmknudson.com/"
languageCode = "en-US"
title = "Heather Knudson"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Heather Knudson"

[params]

  # Metadata for search engines and social sharing
  author = "Heather Knudson"
  description = "Research. Evaluation. Collections Care. Heather Knudson is a Museology MA student at the University of Washington Seattle."
  shareImage = "/social.png"
  #twitterHandle = "onepagelove"

  # Favicon
  favicon = "/favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "/profile.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:knudsh@uw.edu?subject=Hello"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/heatherknudson/"

  #Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Resume"
        url = "/HMKnudson_Resume.pdf"

      # [[params.links.list3.link]]
      #   text = "Link Two"
      #   url = "#"

      # [[params.links.list3.link]]
      #   text = "Link Three"
      #   url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
# the license option via the template author's website: https://onepagelove.com/split
